spring:
  profiles:
    active: window-dev
---
server:
  port: 8080
  
spring:
  profiles: window-dev
  application:
    name: example-batchmanager
  datasource:
    url: jdbc:mariadb://localhost:3306/batch
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
  jpa:
    show-sql: true    
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Batch Meta는 테이블, 컬럼 모두 대문자(모두 대문자 전략 ) 
        
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%-5level] - %msg%n"
  level:
    yongs.temp: DEBUG

---
server:
  port: 8080
  
spring:
  profiles: container
  application:
    name: example-batchmanager
  datasource:
    url: jdbc:mariadb://maria-db:3306/batch
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
  jpa:
    show-sql: false    
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Batch Meta는 테이블, 컬럼 모두 대문자(모두 대문자 전략 ) 
          
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%-5level] - %msg%n"
  level:
    yongs.temp: INFO

